dependencies {
    implementation project(':common:redis')
    implementation project(':common:events')
    implementation project(':common:logging')
    implementation project(':common:exception')
    implementation project(':domain:schedules:core:model')
    implementation project(':domain:schedules:connector:interface')
    implementation project(':domain:schedules:connector:out-bound:open-ai')
    implementation project(':domain:category:connector:interface')
    implementation project(':domain:category:core:model')
    implementation project(':domain:notification:connector:interfaces')
    implementation project(':domain:notification:api:api-model')
    implementation project(':domain:notification:core:service')
    implementation project(':domain:notification:core:model')
    implementation project(':domain:notification:core:mapper')
    implementation project(':domain:notification:core:enumerate')
    implementation project(':domain:notification:infrastructure:rdb')
    implementation 'net.javacrumbs.shedlock:shedlock-spring:5.9.0'
    implementation 'net.javacrumbs.shedlock:shedlock-provider-redis-spring:5.9.0'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'jakarta.mail:jakarta.mail-api:2.1.2'
    implementation 'com.sun.mail:jakarta.mail:2.0.1'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
}