spring:
  mail:
    host: ${MAIL_TEST_HOST:localhost}
    port: ${MAIL_TEST_PORT:2525}
    username: ${MAIL_TEST_USERNAME:test}
    password: ${MAIL_TEST_PASSWORD:test}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000